development:
  sessions:
    default:
      database: unclejosh_development
      hosts:
        - localhost:27017 
production:
  sessions:
    default:
      database: unclejosh_production
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: unclejosh_test
      hosts:
        - localhost:27017

